image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

auth:
  database: priority_notes
  username: notes_user
  password: notes_password

persistence:
  size: 1Gi

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
