apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
