apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: priority-notes-dev
resources:
  - namespace.yaml
  - ../../base
  - secret.yaml
  - hpa.yaml
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
