apiVersion: v1
kind: Secret
metadata:
  name: priority-notes-secret
  labels:
    app: priority-notes
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
stringData:
  APP_SECRET_KEY: {{ .Values.secret.appSecretKey | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
