apiVersion: v1
kind: ConfigMap
metadata:
  name: priority-notes-config
  namespace: lab5
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  POSTGRES_DB: "priority_notes"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
