apiVersion: v1
kind: Secret
metadata:
  name: priority-notes-secret
  namespace: lab5
type: Opaque
stringData:
  APP_SECRET_KEY: ""
  POSTGRES_USER: "notes_user"
  POSTGRES_PASSWORD: "notes_password"
  DATABASE_URL: "postgresql://notes_user:notes_password@postgres-service:5432/priority_notes"
